baseurl = "http://www.gateixeira.com"
title = "gateixeira"

theme = "hugo-coder"
googleAnalytics = "UA-163449981-1"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "Gui"

[params]
    author = "Gui Teixeira"
    description = "Gui's personal website"
    keywords = "blog,developer,personal"
    info = "IT Consultant"
    avatarurl = "images/avatar.jpg"
    footercontent = ""
    favicon_32 = "/images/favicon-32x32.png"
    favicon_16 = "/images/favicon-16x16.png"

    dateformat = "January 2, 2006"

    hidefavCredits = false
    hideCopyright = false
    #since = 2019

    # Git Commit in Footer, uncomment the line below to enable it.
    #commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "auto"

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = []

    # Custom JS
    custom_js = []

# If you want to use fathom(https://usefathom.com) for analytics, add this section
[params.fathomAnalytics]
    siteID = "ABCDE"
    # Default value is cdn.usefathom.com, overwrite this if you are self-hosting
    serverURL = "analytics.example.com"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/gateixeira/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/gateixeira/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 3
    url = "https://twitter.com/gateixeira/"
#[[params.social]]
#    name = "Instagram"
#    icon = "fab fa-instagram"
#    weight = 2
#    url = "https://instagram.com/gateixeira/"
#[[params.social]]
#    name = "Medium"
#    icon = "fab fa-medium"
#    weight = 5
#    url = "https://medium.com/@gui.andrighetto"

[languages]
    [languages.en]
        languagename = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "About"
            weight = 1
            url = "about/"

            [[languages.en.menu.main]]
            name = "Blog"
            weight = 2
            url = "posts/"

            [[languages.en.menu.main]]
            name = "Projects"
            weight = 3
            url = "projects/"

            [[languages.en.menu.main]]
            name = "Contact me"
            weight = 5
            url = "contact/"


    [languages.pt-br]
        languagename = "Português"

        [languages.pt-br.params]
            info = "Consultor de TI"
            description = "Site pessoal do Guilherme Teixeira"
            keywords = "blog,desenvolvedor,pessoal"
            footercontent = ""

        [languages.pt-br.menu]

            [[languages.pt-br.menu.main]]
            name = "Sobre"
            weight = 1
            url = "about/"

            #$[[languages.pt-br.menu.main]]
            #name = "Blog"
            #weight = 2
            #url = "posts/"

            [[languages.pt-br.menu.main]]
            name = "Projetos"
            weight = 3
            url = "projects/"

            [[languages.pt-br.menu.main]]
            name = "Contato"
            weight = 5
            url = "contact/"

    [languages.de-de]
        languagename = "Deutsch"

        [languages.de-de.params]
            info = "IT-Berater"
            description = "Gui's persönliche Webseite"
            keywords = "blog,entwickler,webseite"
            footercontent = ""

        [languages.de-de.menu]

            [[languages.de-de.menu.main]]
            name = "Über mich"
            weight = 1
            url = "about/"

            #[[languages.de-de.menu.main]]
            #name = "Blog"
            #weight = 2
            #url = "posts/"

            [[languages.de-de.menu.main]]
            name = "Projekte"
            weight = 3
            url = "projects/"

            [[languages.de-de.menu.main]]
            name = "Kontakt"
            weight = 5
            url = "contact/"
[deployment]
# By default, files are uploaded in an arbitrary order.
# Files that match the regular expressions in the "Order" list
# will be uploaded first, in the listed order.
order = [".jpg$", ".gif$"]


[[deployment.targets]]
# An arbitrary name for this target.
name = "personal"
# The Go Cloud Development Kit URL to deploy to. Examples:
# GCS; see https://gocloud.dev/howto/blob/#gcs
 URL = "gs://www.gateixeira.com"

# S3; see https://gocloud.dev/howto/blob/#s3
# For S3-compatible endpoints, see https://gocloud.dev/howto/blob/#s3-compatible
# URL = "s3://<Bucket Name>?region=<AWS region>"

# Azure Blob Storage; see https://gocloud.dev/howto/blob/#azure
# URL = "azblob://$web"

# You can use a "prefix=" query parameter to target a subfolder of the bucket:
# URL = "gs://<Bucket Name>?prefix=a/subfolder/"

# If you are using a CloudFront CDN, deploy will invalidate the cache as needed.
#cloudFrontDistributionID = <ID>


# ... add more [[deployment.targets]] sections ...


# [[deployment.matchers]] configure behavior for files that match the Pattern.
# Samples:

[[deployment.matchers]]
#  Cache static assets for 1 year.
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true
